### ISSUE TITLE
Use the ASP.NET base image?

### ISSUE THREAD

**Issue by shirhatti** [sixeyed/nerd-dinner#2]
I just stumbled across your nerd-dinner tutorial series. Is there any reason you chose against using the [ASP.NET base image](https://github.com/Microsoft/aspnet-docker/blob/master/4.6.2/Dockerfile)?

**Comment by sixeyed** [comment]
In the early posts I wanted to show that you can install Windows features, and I also wanted to see what the update process was for the ASP.NET images. It seems the ASP.NET images are updated alongside the base Server Core image, so I'm happy to use them now. Next post will move to those images and show CI/CD too.
