### ISSUE TITLE
To be continue...

### ISSUE THREAD

**Issue by ShurikEv** [sixeyed/nerd-dinner#4]
When will the continuation of the series of posts?

**Comment by sixeyed** [comment]
The Nerd Dinner project got rolled into my book, [Docker on Windows](https://www.amazon.com/Docker-Windows-Elton-Stoneman-ebook/dp/B0711Y4J9K/). I am blogging about all the images in that book in my [Weekly Windows Dockerfile](https://blog.sixeyed.com/tag/weekly-dockerfile/) series, but it will be a while before I get to the Nerd Dinner ones :)
