### ISSUE TITLE
image operating system "windows" cannot be used on this platform.

### ISSUE THREAD

**Issue by polajenko** [sixeyed/nerd-dinner#5]
I am trying to run this by typing 
docker run -d -p 80:8081 sixeyed/nerd-dinner:part1

but I receive the following error:
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: image operating system "windows" cannot be used on this platform.

I am running windows 10 Enterprise with Docker for windows Version 17.09.0-ce-win33 (13620)

**Comment by GozPaez** [comment]
Hello Alex in this moment, I have the same issue, How did you solve this?

I have Docker version 18.09.0 in OS - Windows 10

**Comment by GozPaez** [comment]
Haha Sorry, I solved my issue, I had the configuration with **Linux containers** , I only changed to windows containers and all run correctly
